env:
    global:
        - CARGO_TARGET_DIR="$TRAVIS_BUILD_DIR/target"

language: rust
rust:
    - nightly
os:
    - linux
sudo: false
addons:
    apt:
        sources:
            - kalakris-cmake
        packages:
            - cmake
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
cache:
    directories:
        - youmu
        - target

script:
    - .travis/script.sh
